---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - /Applications/Dash.app
    folders:
    - path: ~/
    - path: ~/Documents
    - path: ~/src/github.com
    - path: ~/Downloads
      sort: datemodified
  - role: dashboard
    disabled: YES
  - role: gatekeeper
    gatekeeper: disable
  - role: computername
    computername: automata

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # cli
  ## config
  - role: git_config
    git_user_name: phillipalexander
    git_user_email: git@phillipalexander.io
  - role: hub
  ## languages
  - role: brew_package
    package_name: node
  - role: rbenv
  - role: npm_package
    package_name: coffee-script
  - role: cask_package
    package_name: java
  # tooling
  - role: npm_package
    package_name: grunt
  - role: npm_package
    package_name: bower
  - role: npm_package
    package_name: mocha
  - role: npm_package
    package_name: node-inspector
  - role: npm_package
    package_name: yo
  - role: brew_package
    package_name: vim
  - role: brew_package
    package_name: ack
  - role: brew_package
    package_name: zsh
  - role: brew_package
    package_name: figlet
  - role: brew_package
    package_name: tree
  - role: brew_package
    package_name: wget
  - role: brew_package
    package_name: htop
  - role: brew_package
    package_name: tmux
  - role: brew_package
    package_name: fasd
  - role: brew_package
    package_name: ssh-copy-id
  - role: spf13_vim

  ## databases
  - role: brew_package
    package_name: postgres
  - role: brew_package
    package_name: mongodb
  - role: brew_package
    package_name: redis
  - role: brew_package
    package_name: elasticsearch
  - role: brew_package
    package_name: mysql
  - role: brew_package
    package_name: sqlite
  ## vms
  - role: cask_package
    package_name: virtualbox
  - role: cask_package
    package_name: vagrant
  ## deployment
  - role: node_package
    package_name: azure-cli
  # - role: brew_package
  #   package_name: ansible # Hey ! Already there !

  # gui
  ## text editors
  - role: cask_package
    package_name: atom
  - role: cask_package
    package_name: mou
  - role: cask_package
    package_name: sublime-text3
  - role: cask_package
    package_name: evernote
  ## tooling
  - role: cask_package
    package_name: alfred
  - role: cask_package
    package_name: flux
  - role: cask_package
    package_name: dash
  - role: cask_package
    package_name: appcleaner
  - role: cask_package
    package_name: clamxav
  - role: cask_package
    package_name: slate
  - role: cask_package
    package_name: amethyst
  - role: cask_package
    package_name: gfxcardstatus
  ## dev tools
  - role: cask_package
    package_name: kaleidoscope
  - role: cask_package
    package_name: transmission
  - role: cask_package
    package_name: vmware-fusion
  - role: cask_package
    package_name: recordit
  - role: cask_package
    package_name: karabiner
  ## browsers
  - role: cask_package
    package_name: google-chrome
  - role: cask_package
    package_name: google-chrome-canary
  ## sync
  - role: cask_package
    package_name: google-drive
  - role: cask_package
    package_name: dropbox
  ## graphics
  - role: cask_package
    package_name: vlc
  - role: cask_package
    package_name: screenflow
  ## communication
  - role: cask_package
    package_name: hipchat
  - role: cask_package
    package_name: google-hangouts
  ## other
  - role: cask_package
    package_name: makerware
